// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDCOp6jc3rcLsi3wXgqNhQYaSR862vTQY',
    appId: '1:357533438685:web:d6ca4fcd4ad04e6c434134',
    messagingSenderId: '357533438685',
    projectId: 'my-finance-25',
    authDomain: 'my-finance-25.firebaseapp.com',
    storageBucket: 'my-finance-25.firebasestorage.app',
    measurementId: 'G-D3DCP32C4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeOa4VtZHXEuL6n-ymzntLuIehmZY83zg',
    appId: '1:357533438685:android:23f5b0d8f49b1e9f434134',
    messagingSenderId: '357533438685',
    projectId: 'my-finance-25',
    storageBucket: 'my-finance-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMOXNIIzazQqYgHjmiCy1vAkVTSqAP2Q',
    appId: '1:357533438685:ios:62658b0f22260ac7434134',
    messagingSenderId: '357533438685',
    projectId: 'my-finance-25',
    storageBucket: 'my-finance-25.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMOXNIIzazQqYgHjmiCy1vAkVTSqAP2Q',
    appId: '1:357533438685:ios:62658b0f22260ac7434134',
    messagingSenderId: '357533438685',
    projectId: 'my-finance-25',
    storageBucket: 'my-finance-25.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDCOp6jc3rcLsi3wXgqNhQYaSR862vTQY',
    appId: '1:357533438685:web:14e8b12b8ede75b7434134',
    messagingSenderId: '357533438685',
    projectId: 'my-finance-25',
    authDomain: 'my-finance-25.firebaseapp.com',
    storageBucket: 'my-finance-25.firebasestorage.app',
    measurementId: 'G-1PB6QFNSDV',
  );
}
